name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag strato-dyndns:$(date +%s)

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.Docker_container}}

    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/HoekieN/store:latest
        docker push ghcr.io/HoekieN/store:latest
